##---------------------------------------------------------------------------##
# CLIENT Configuration
##---------------------------------------------------------------------------##
debug: ${DEBUG_MODE:false}

server:
  port: ${SERVER_PORT:8090}

##---------------------------------------------------------------------------##
spring:
  application:
    name: hystrix-client


serviceId: ${SERVICE_ID:microservice-producer}


##---------------------------------------------------------------------------##
logging:
  level:
    root: 'INFO'
    org.springframework: 'ERROR'
    org.springframework.web: 'INFO'

##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  # {status: UP}
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
#management.endpoint.hystrix.config:

# To enable/disable Hystrix in Feign
feign:
  hystrix:
    enabled: true

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

##---------------------------------------------------------------------------##
#spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
