##---------------------------------------------------------------------------##
# CLIENT Configuration
##---------------------------------------------------------------------------##

server:
  port: ${SERVER_PORT:8090}

##---------------------------------------------------------------------------##
spring:
  application:
    name: ribbon-client


serviceId: ${SERVICE_ID:microservice-producer}



##---------------------------------------------------------------------------##
# Ribbon:
ribbon:
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  OkToRetryOnAllOperations: true



##---------------------------------------------------------------------------##
logging:
  level:
    root: 'INFO'
    org.springframework: 'ERROR'
    org.springframework.web: 'INFO'

##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
