##---------------------------------------------------------------------------##
# RabbitMq Solution Configuration
##---------------------------------------------------------------------------##
debug: ${DEBUG_MODE:false}

server:
  port: ${SERVER_PORT:8761}

##---------------------------------------------------------------------------##
spring:
  application:
    name: eureka-server

  #---------------- RabbitMQ -----------------#
  rabbitmq:
    #Default username and pass
    dynamic: true
#    host: mfk
    port: 5672
    username: guest
    password: guest

jsa.rabbitmq.queue: jsa.myqueue1
jsa.rabbitmq.exchange: jsa.direct1
#jsa.rabbitmq.routingkey: jsa.routingkey1
#jsa.rabbitmq.exchange: jsa.fanout

queue.name: msQueue
queue.demo.name: msDemoQueue


##---------------------------------------------------------------------------##
logging:
  level:
    root: 'INFO'
    org.springframework: 'ERROR'

##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
#spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

#spring.boot.admin.client.url: "http://localhost:1111"
spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
