##---------------------------------------------------------------------------##
# CLIENT Configuration
##---------------------------------------------------------------------------##
debug: ${DEBUG_MODE:false}

server:
  port: ${SERVER_PORT:8090}

##---------------------------------------------------------------------------##
spring:
  application:
    name: microservice-client


serviceId: ${SERVICE_ID:microservice-producer}
serviceId2: ${SERVICE_ID:microservice-producer} #SERVICE_ID: microservice-producer.1.2


##---------------------------------------------------------------------------##
logging:
  level:
    root: 'INFO'
    org.springframework: 'ERROR'

##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

#spring.boot.admin.client.url: "http://localhost:1111"
spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
